services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: games-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d games-db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  seed:
    build: ./backend/db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: games-db
    depends_on:
      db:
        condition: service_healthy

  api:
    build: ./backend
    environment:
      DATABASE_URL: postgres://admin:123@db:5432/games-db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      seed:
        condition: service_completed_successfully

  web:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  pgdata: